# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [5]:
# your code here
print(np.__version__)

1.26.4


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1
a1 = np.random.rand(2, 3, 5)
print("Method 1 (np.random.rand):")
print(a1)
print("-" * 30)


Method 1 (np.random.rand):
[[[0.55489761 0.52215766 0.1777261  0.9706489  0.59542698]
  [0.19588648 0.63544374 0.38936941 0.25937805 0.06410254]
  [0.02942429 0.36907084 0.611095   0.05324023 0.33777398]]

 [[0.43211409 0.20552325 0.6372899  0.38605468 0.83723968]
  [0.55019267 0.98546949 0.72400853 0.69467995 0.35497837]
  [0.62842653 0.42893437 0.82922228 0.99290969 0.31279557]]]
------------------------------


In [9]:
# Method 2
a2 = np.random.random((2, 3, 5)) # Note the tuple for shape
print("Method 2 (np.random.random):")
print(a2)
print("-" * 30)

Method 2 (np.random.random):
[[[0.82506564 0.67020864 0.65654948 0.98768239 0.85672679]
  [0.02489396 0.35997317 0.09212523 0.67433799 0.80711975]
  [0.14801298 0.18100381 0.17499139 0.52652573 0.4402478 ]]

 [[0.42751513 0.6037491  0.63474168 0.02136154 0.67355362]
  [0.36193013 0.52775382 0.44309801 0.52327135 0.02160817]
  [0.93572784 0.15491944 0.21485649 0.80215312 0.50989124]]]
------------------------------


In [11]:
# Method 3
a3 = np.random.uniform(low=0.0, high=1.0, size=(2, 3, 5))
print("Method 3 (np.random.uniform):")
print(a3)
print("-" * 30)

Method 3 (np.random.uniform):
[[[0.57015743 0.34620411 0.11931744 0.4682635  0.27201211]
  [0.40599849 0.01726833 0.38067657 0.06469745 0.69058513]
  [0.73332883 0.70392604 0.77278583 0.60190115 0.46050454]]

 [[0.94522324 0.75330298 0.39462454 0.44070921 0.98358375]
  [0.61640058 0.14711367 0.39840991 0.71207494 0.14179984]
  [0.06580223 0.81911784 0.10869111 0.86905504 0.7556885 ]]]
------------------------------


#### 4. Print *a*.


In [13]:
# your code here
a = np.random.rand(2, 3, 5)
print("Array 'a':")
print(a)
print("-" * 30)

Array 'a':
[[[0.4154846  0.36998254 0.10703768 0.31675963 0.38980084]
  [0.25528918 0.19342652 0.41600396 0.0415491  0.98545347]
  [0.5653737  0.6218206  0.10252092 0.2045922  0.17441913]]

 [[0.61445548 0.12387525 0.57881098 0.9307921  0.48004131]
  [0.45796013 0.9551636  0.18621743 0.76986565 0.04543139]
  [0.60101173 0.01351298 0.43573448 0.09380919 0.75168889]]]
------------------------------


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [17]:
# your code here
b = np.random.rand(5, 2, 3)


#### 6. Print *b*.


In [19]:
# your code here
print("Array 'b':")
print(b)
print("-" * 30)

Array 'b':
[[[0.7357006  0.8217884  0.88908191]
  [0.62153886 0.19128482 0.12541327]]

 [[0.17219984 0.31449053 0.52744912]
  [0.38444805 0.27740291 0.46931332]]

 [[0.5132881  0.1101247  0.96582432]
  [0.74453746 0.13011145 0.93423982]]

 [[0.09797331 0.02963819 0.68077718]
  [0.17796342 0.49997905 0.5516664 ]]

 [[0.15191942 0.93166937 0.47145316]
  [0.76904903 0.9573475  0.70792625]]]
------------------------------


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [21]:
# your code here
same_size_elements = a.size == b.size
print(f"Do a and b have the same total number of elements? {same_size_elements}")

print(f"Shape of a: {a.shape}")
print(f"Shape of b: {b.shape}")

# To rigorously prove if they have the "same size" in terms of dimensions and number of elements:
# While they have the same *number of elements* (2*3*5 = 30 and 5*2*3 = 30),
# they do *not* have the same *shape* or *structure*.
print("Proof: 'a.size' (total elements) vs 'a.shape' (dimensions):")
print(f"a.size: {a.size}")
print(f"b.size: {b.size}")
print(f"a.shape: {a.shape}")
print(f"b.shape: {b.shape}")
print("-" * 30)

Do a and b have the same total number of elements? True
Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)
Proof: 'a.size' (total elements) vs 'a.shape' (dimensions):
a.size: 30
b.size: 30
a.shape: (2, 3, 5)
b.shape: (5, 2, 3)
------------------------------


#### 8. Are you able to add *a* and *b*? Why or why not?


In [23]:
# your answer here
try:
    d_attempt = a + b
except ValueError as e:
    print(f"Attempting to add a and b resulted in an error: {e}")
    print("Explanation: We are NOT able to add 'a' and 'b' directly.")
    print("This is because for element-wise operations like addition, NumPy requires the arrays to have compatible shapes.")
    print("In this case, 'a' has shape (2, 3, 5) and 'b' has shape (5, 2, 3).")
    print("NumPy's broadcasting rules cannot align these two different shapes for direct addition.")
print("-" * 30)

Attempting to add a and b resulted in an error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
Explanation: We are NOT able to add 'a' and 'b' directly.
This is because for element-wise operations like addition, NumPy requires the arrays to have compatible shapes.
In this case, 'a' has shape (2, 3, 5) and 'b' has shape (5, 2, 3).
NumPy's broadcasting rules cannot align these two different shapes for direct addition.
------------------------------


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [25]:
# your code here
c = b.transpose((1, 2, 0)) 
print("Shape of original b:", b.shape)
print("Shape of transposed c:", c.shape)
print("-" * 30)

Shape of original b: (5, 2, 3)
Shape of transposed c: (2, 3, 5)
------------------------------


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [29]:
# your code/answer here
d = a + c
print("Sum of a and c (d):")
print(d)
print("\nExplanation: Adding 'a' and 'c' works now because they have the exact same shape:")
print(f"Shape of a: {a.shape}")
print(f"Shape of c: {c.shape}")
print("NumPy can perform element-wise addition directly when arrays have identical shapes,")
print("-" * 30)

Sum of a and c (d):
[[[1.15118521 0.54218238 0.62032578 0.41473293 0.54172026]
  [1.07707758 0.50791705 0.52612867 0.07118729 1.91712284]
  [1.45445561 1.14926972 1.06834524 0.88536937 0.64587229]]

 [[1.23599435 0.5083233  1.32334844 1.10875552 1.24909034]
  [0.64924495 1.2325665  0.31632887 1.2698447  1.00277889]
  [0.72642499 0.48282631 1.36997431 0.64547559 1.45961514]]]

Explanation: Adding 'a' and 'c' works now because they have the exact same shape:
Shape of a: (2, 3, 5)
Shape of c: (2, 3, 5)
NumPy can perform element-wise addition directly when arrays have identical shapes,
------------------------------


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [31]:
# your code/answer here
print("Array 'a':")
print(a)
print("\nArray 'd' (a + c):")
print(d)

print("\nExplanation of the difference and relation between 'a' and 'd':")
print("Array 'd' is the result of adding 'a' and 'c' (the transposed 'b').")
print("Since all elements in 'b' (and thus 'c') were initially 1, adding 'c' to 'a' means that each element in 'd'")
print("is simply the corresponding element in 'a' plus 1.")
print("In other words, d[i, j, k] = a[i, j, k] + 1 for all indices i, j, k.")
print("You can verify this by looking at the values: each value in 'd' is exactly 1 greater than the value in the same position in 'a'.")

Array 'a':
[[[0.4154846  0.36998254 0.10703768 0.31675963 0.38980084]
  [0.25528918 0.19342652 0.41600396 0.0415491  0.98545347]
  [0.5653737  0.6218206  0.10252092 0.2045922  0.17441913]]

 [[0.61445548 0.12387525 0.57881098 0.9307921  0.48004131]
  [0.45796013 0.9551636  0.18621743 0.76986565 0.04543139]
  [0.60101173 0.01351298 0.43573448 0.09380919 0.75168889]]]

Array 'd' (a + c):
[[[1.15118521 0.54218238 0.62032578 0.41473293 0.54172026]
  [1.07707758 0.50791705 0.52612867 0.07118729 1.91712284]
  [1.45445561 1.14926972 1.06834524 0.88536937 0.64587229]]

 [[1.23599435 0.5083233  1.32334844 1.10875552 1.24909034]
  [0.64924495 1.2325665  0.31632887 1.2698447  1.00277889]
  [0.72642499 0.48282631 1.36997431 0.64547559 1.45961514]]]

Explanation of the difference and relation between 'a' and 'd':
Array 'd' is the result of adding 'a' and 'c' (the transposed 'b').
Since all elements in 'b' (and thus 'c') were initially 1, adding 'c' to 'a' means that each element in 'd'
is simply th

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [33]:
# your code here
e = a * c

print("Result of a * c (e):")
print(e)
print("-" * 30)

Result of a * c (e):
[[[0.30567227 0.06371094 0.05494117 0.03103399 0.05921832]
  [0.20979369 0.06083081 0.04581231 0.00123144 0.91811681]
  [0.50266353 0.32797873 0.0990172  0.1392817  0.08223045]]

 [[0.38190796 0.0476236  0.43094646 0.16564694 0.3691753 ]
  [0.08760082 0.26496516 0.02422902 0.3849167  0.04349362]
  [0.07537484 0.00634182 0.40708051 0.05175138 0.5321403 ]]]
------------------------------


#### 13. Does *e* equal to *a*? Why or why not?


In [39]:
print("\nExplanation:")
print("No, 'e' does not equal to 'a'.")
print("Array 'e' is the result of element-wise multiplication of 'a' and 'c'.")
print("Since all elements in 'c' are 1 (because 'b' was all ones and 'c' is just a transposed 'b'),")
print("multiplying 'a' by 'c' means each element of 'a' is multiplied by 1.")
print("Mathematically, a[i, j, k] * c[i, j, k] = a[i, j, k] * 1 = a[i, j, k].")
print("Therefore, 'e' should be exactly equal to 'a'.")
print("If `np.array_equal(e, a)` returns False, it might be due to floating-point precision issues if 'a' was generated with very small numbers or if intermediate calculations introduced tiny discrepancies.")
print("However, conceptually, `a * 1` should be `a`.")
if np.allclose(e, a):
    print("Correction: Using np.allclose (which accounts for floating-point precision), e IS essentially equal to a.")
    print("The previous `np.array_equal` might return False due to minute floating point differences that are practically zero.")
else:
    print("Even with `np.allclose`, e is not equal to a. This would be unexpected given the operation (a * 1).")

print("-" * 30)



Explanation:
No, 'e' does not equal to 'a'.
Array 'e' is the result of element-wise multiplication of 'a' and 'c'.
Since all elements in 'c' are 1 (because 'b' was all ones and 'c' is just a transposed 'b'),
multiplying 'a' by 'c' means each element of 'a' is multiplied by 1.
Mathematically, a[i, j, k] * c[i, j, k] = a[i, j, k] * 1 = a[i, j, k].
Therefore, 'e' should be exactly equal to 'a'.
If `np.array_equal(e, a)` returns False, it might be due to floating-point precision issues if 'a' was generated with very small numbers or if intermediate calculations introduced tiny discrepancies.
However, conceptually, `a * 1` should be `a`.
Even with `np.allclose`, e is not equal to a. This would be unexpected given the operation (a * 1).
------------------------------


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [41]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f"Max value in d: {d_max}")
print(f"Min value in d: {d_min}")
print(f"Mean value in d: {d_mean}")
print("-" * 30)

Max value in d: 1.9171228398785811
Min value in d: 0.07118729296595738
Mean value in d: 0.9051161476019403
------------------------------


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [43]:
# your code here
f = np.empty(d.shape)

print(f"Shape of newly created empty array f: {f.shape}")
print("Content of empty array f (will contain uninitialized/garbage values):")
print(f)
print("-" * 30)

Shape of newly created empty array f: (2, 3, 5)
Content of empty array f (will contain uninitialized/garbage values):
[[[4.16484603e-06 3.70982538e-06 1.08037683e-06 3.17759627e-06
   3.90800839e-06]
  [2.56289181e-06 1.94426522e-06 4.17003963e-06 4.25491026e-07
   9.86453466e-06]
  [5.66373700e-06 6.22820602e-06 1.03520920e-06 2.05592198e-06
   1.75419128e-06]]

 [[6.15455483e-06 1.24875250e-06 5.79810980e-06 9.31792100e-06
   4.81041314e-06]
  [4.58960130e-06 9.56163596e-06 1.87217425e-06 7.70865650e-06
   4.64313871e-07]
  [6.02011726e-06 1.45129848e-07 4.36734484e-06 9.48091885e-07
   7.52688893e-06]]]
------------------------------


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [47]:
# your code here
f[d == d_min] = 0
f[d == d_max] = 100
f[np.isclose(d, d_mean)] = 50
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
print("Array 'f' after populating based on 'd' values:")
print(f)

Array 'f' after populating based on 'd' values:
[[[ 75.  25.  25.  25.  25.]
  [ 75.  25.  25.   0. 100.]
  [ 75.  75.  75.  25.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 25.  25.  75.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [49]:
# your code here
print("Array 'd':")
print(d)
print("\n" + "="*50 + "\n") 

print("Array 'f':")
print(f)
print("\n" + "="*50 + "\n") 

Array 'd':
[[[1.15118521 0.54218238 0.62032578 0.41473293 0.54172026]
  [1.07707758 0.50791705 0.52612867 0.07118729 1.91712284]
  [1.45445561 1.14926972 1.06834524 0.88536937 0.64587229]]

 [[1.23599435 0.5083233  1.32334844 1.10875552 1.24909034]
  [0.64924495 1.2325665  0.31632887 1.2698447  1.00277889]
  [0.72642499 0.48282631 1.36997431 0.64547559 1.45961514]]]


Array 'f':
[[[ 75.  25.  25.  25.  25.]
  [ 75.  25.  25.   0. 100.]
  [ 75.  75.  75.  25.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 25.  25.  75.  25.  75.]]]




#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [59]:
# your code here
f_str = np.empty(d.shape, dtype=object)
f_str[d == d_min] = "A"
f_str[d == d_max] = "E"
f_str[np.isclose(d, d_mean)] = "C"
f_str[(d > d_min) & (d < d_mean)] = "B"
f_str[(d > d_mean) & (d < d_max)] = "D"

print("Result (f_str with string labels):")
print(f_str)
print("-" * 30)

Result (f_str with string labels):
[[['D' 'B' 'B' 'B' 'B']
  ['D' 'B' 'B' 'A' 'E']
  ['D' 'D' 'D' 'B' 'B']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'D' 'B' 'D' 'D']
  ['B' 'B' 'D' 'B' 'D']]]
------------------------------
